name: "CI"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - run: |
        gem i slather --no-rdoc
        bundle exec rake specs:ios
        bundle exec rake specs:osx
